title: Adeleke Kafayat # your name (or website title) here
logo: "fade.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  <br><br>
  Mechanical Engineer 
  <br><br>
  <a href="https://www.linkedin.com/in/kafayat-adeleke-64a040206/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
